Move config to use mappings
quarkiverse/quarkus-vault pull request #140
Opened 2023-06-15 10:33 UTC by radcortez

2023-06-19 15:51 UTC, vsevel commented
hello @radcortez nice improvement
the only drawback I see are disappearance of custom `toString` methods, where we would display sensitive information according to a log confidentiality level.

see https://github.com/quarkiverse/quarkus-vault/blob/main/runtime/src/main/java/io/quarkus/vault/runtime/config/VaultBootstrapConfig.java#L276

in summary 
- we can't have a `toString()` that prints out all fields, 
- we have to display some non sensitive fields
- ideally, we want to display some sensitive field according to a configurable sensitive level

2023-06-20 15:58 UTC, radcortez commented
Yes, that is something that I don't know how to handle.

Mappings are able to generate a plain `toString` method, but obviously, they are not aware of a sensitive level. The `toString` method is generated as is.

Unfortunately, we cannot provide a default method of `toString` (to provide our implementation). Providing some sort of hook to influence the generation of `toString` method seems like an overkill to me.

Would it be acceptable to provide the implementation under a different method signature?

2023-06-21 07:11 UTC, vsevel commented
> Would it be acceptable to provide the implementation under a different method signature?

yes.

if we do not support sensitivity, it would be worthwile at least to introduce some annotation `@Confidential` that we can put on individual fields so that they get displayed as `token=XXXXXX`

2023-07-20 11:03 UTC, radcortez commented
The latest Quarkus version resolved some issues with the documentation generator, so this should be mostly ready now.

Mappings with plain `toString` use the generated `toString` from the implementation. The one with visibilities, I had to add a new method signature to be able to provide a `toString` implementation. It takes the level as the argument to control what is printed.

> if we do not support sensitivity, it would be worthwile at least to introduce some annotation `@Confidential` that we can put on individual fields so that they get displayed as `token=XXXXXX`

One issue we have with current Mappings and the old classes is that even with such annotation, the secret is still available and cached in the Config. One idea is to provide a specific type to represent secrets. This would allow us to query the secret only when required and never cache the value.

2023-07-23 17:36 UTC, vsevel commented
I tried logging a config class with your changes:

```
    public Uni<String> getClientToken(VaultClient vaultClient) {
        log.info("XXXXXXXX " + getConfig().authentication());
        return getConfig().authentication().isDirectClientToken() ? getDirectClientToken(vaultClient)
                : login(vaultClient).map(vaultToken -> vaultToken.clientToken);
    }
```

I get:
```
2023-07-23 19:27:52,667 INFO  [io.qua.vau.run.VaultAuthManager] (main) XXXXXXXX io.quarkus.vault.runtime.config.VaultAuthenticationConfig1335487764Impl@5b0e9e0c
```

is this what you mean when saying _Mappings with plain toString use the generated toString from the implementation. _?
the generated `toString` from the implementation comes from `Object`?

> The one with visibilities, I had to add a new method signature to be able to provide a toString implementation. It takes the level as the argument to control what is printed.

how does it work?
is it supposed to be on the interface?

2023-07-24 08:20 UTC, vsevel commented
I see it now @radcortez , in `VaultBootstrapConfig`. I thought it was in other config classes too.

however, the semantic has been broken. when we mask with a tolerance, the argument should be the level at which you may show the value for that particular attribute. it will be different from one attribute to another, and it must be hardcoded (or ideally retrieved from the field definition if we had some annotations).

so instead of:
```
clientToken=" + logConfidentialityLevel().maskWithTolerance(authentication().clientToken().orElse(""), level)
```
this should be:
```
clientToken=" + logConfidentialityLevel().maskWithTolerance(authentication().clientToken().orElse(""),LogConfidentialityLevel.LOW)
```

`kubernetesAuthenticationRole, userpassUsername, appRoleRoleId` are `MEDIUM`
`userpassPassword, appRoleSecretId, appRoleSecretIdWrappingToken, clientToken, clientTokenWrappingToken` are `LOW`

and there is no need for an argument in the new `toString` method.
a suggestion is to call it `toSecuredString` or `toConfidentialString`:

```
    default String toSecuredString() {
        return "VaultRuntimeConfig{" +
                "url=" + url() +
                ...
                ", clientToken="
                + logConfidentialityLevel().maskWithTolerance(authentication().clientToken().orElse(""),
                        LogConfidentialityLevel.LOW)
```

`VaultBootstrapConfig` could be renamed `VaultRuntimeConfig` now.

also there are some conflicts with `main`

once we have this in, I would like to cut a release.

2023-07-24 08:26 UTC, vsevel requested changes

2023-07-24 08:26 UTC, vsevel commented on runtime/src/main/java/io/quarkus/vault/runtime/config/VaultBootstrapConfig.java
> +public interface VaultBootstrapConfig {
rename to `VaultRuntimeConfig`

2023-07-24 08:26 UTC, vsevel commented on runtime/src/main/java/io/quarkus/vault/runtime/config/VaultBootstrapConfig.java
> +    default String toString(LogConfidentialityLevel level) {
rename to `toSecuredString()` with no argument
hardcode the level for each attribute, according to their own sensitivity

2023-07-24 10:25 UTC, radcortez commented
Yes, you require a `toString` method declaration on each interface to generate the implementation.

2023-07-24 14:17 UTC, vsevel approved these changes

2023-07-24 14:39 UTC, merged

2023-07-24 14:40 UTC, vsevel commented
thanks for this cool update @radcortez !